### ISSUE TITLE
Support .net 4.0

### ISSUE THREAD

**Issue by abadyl** [azure-contrib/AzureDirectory#18]
Hi,
Is it possible to add support of .net 4.0

In out example we are using Umbraco 6.\* and we can't migrate out solution to 4.5

I checked and if to replace Mutex.TryOpenExisting with custom reslization, then it should be possible to run under 4.0

Best regards,
Alexey Badyl

**Comment by richorama** [comment]
happy if you want to submit a PR, although most people are moving over to using the azure search service now....
