### ISSUE TITLE
The remote server returned an error: (404) Not Found.

### ISSUE THREAD

**Issue by jbreuer** [azure-contrib/AzureDirectory#20]
I'm using AzureDirectory and I'm getting this error: The remote server returned an error: (404) Not Found.

More info in this topic: https://our.umbraco.org/forum/extending-umbraco-and-using-the-api/78818-using-azuredirectory-with-examine

**Comment by richorama** [comment]
Could you see if this commit has fixed the issue:

https://github.com/azure-contrib/AzureDirectory/commit/a2bb7aaf55f70b204c34abec0d0dce6d4b5d0386

**Comment by jbreuer** [comment]
I tried that myself, but in the catch event you also need the blob variable. So the code in a2bb7aa wont build.

**Comment by richorama** [comment]
you're right, I've just fixed that (sorry!)
