### ISSUE TITLE
Help for Mongo Implementation

### ISSUE THREAD

**Issue by SebastianStehle** [azure-contrib/AzureDirectory#35]
Hi @richorama

Seems that we share a lot of tech stacks. I have working on an improvement of a indexer solution based on Orleans and then I found this project. I have taken the idea to implement a custom directory and "adapted" your code to MongoDB:

https://github.com/Squidex/squidex/tree/text-indexer/backend/src/Squidex.Domain.Apps.Entities.MongoDb/FullText

I have not done so much around locking as the code is only used in a grain. But if you have time it would be great if you can review it. Perhaps as part of this PR: https://github.com/Squidex/squidex/pull/454

**Comment by richorama** [comment]
Hi @SebastianStehle, small world!

I sort of adopted this repo (I'm not sure why!), without knowing too much about Lucene internals, so I'm more of a janitor than a develop on this one.
